name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.5
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - ydata-profiling=4.6.3
  - pyarrow=12.0.1
  - ipywidgets=8.1.1
  - entrypoints
  - pip:
      - wandb==0.16.0
      - ipython==8.16.1
